# Generated by Django 5.1.2 on 2024-10-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('Generos_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Generos',
            },
        ),
    ]
